dist: xenial
language: python

stages:
- name: test
  if: tag IS NOT present
- name: deploy
  if: repo = napari/naplugi AND tag IS present

jobs:
  include:
    - python: '3.6'
      env: TOXENV=linting
      cache:
        directories:
          - $HOME/.cache/pre-commit
    - python: '3.6'
      env: TOXENV=docs
    - python: '3.6'
      env: TOXENV=py36-coverage
    - python: '3.7'
      env: TOXENV=py37-coverage
    - python: '3.8'
      env: TOXENV=py38-coverage

    # - stage: deploy
    #   python: '3.8'
    #   env:
    #   install: pip install -U setuptools
    #   script: skip
    #   deploy:
    #     provider: pypi
    #     user: nicoddemus
    #     distributions: sdist bdist_wheel
    #     skip_upload_docs: true
    #     password:
    #       secure: PDvQCKfXrF1V/tdwEOfeDEjDs6vJ9gKWo4yrMUmBx1JL5plHZaqfHLftlGMoHekaQTHcfyYYbxignFw5IGsn97/nFKKWDPNBfZA+3RJJmeJfz2NQunYkSnoqtBtfEtWHzFPdkCm0w/CN9C8IpRjhvLnFTUQzil6iMy6wZG276gU=
    #     on:
    #       tags: true
    #       repo: napari/naplugi

install:
  - pip install -U pip
  - pip install -U --force-reinstall setuptools tox

script:
  - tox

after_script:
  - |
    if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
      bash <(curl -s https://codecov.io/bash) -Z -X fix -f coverage.xml -n $TOXENV
    fi
